/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health verifica se a API está em execução.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recursos/{id_recurso}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar Por Id */
        get: operations["buscar_por_id_api_recursos__id_recurso__get"];
        put?: never;
        post?: never;
        /** Remover */
        delete: operations["remover_api_recursos__id_recurso__delete"];
        options?: never;
        head?: never;
        /** Atualizar */
        patch: operations["atualizar_api_recursos__id_recurso__patch"];
        trace?: never;
    };
    "/api/recursos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar */
        get: operations["listar_api_recursos_get"];
        put?: never;
        /** Criar */
        post: operations["criar_api_recursos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recursos/{id_recurso}/disponibilidade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Disponibilidade */
        get: operations["disponibilidade_api_recursos__id_recurso__disponibilidade_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renovar */
        post: operations["renovar_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Criar */
        post: operations["criar_api_usuarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservas/{id_reserva}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar Por Id */
        get: operations["buscar_por_id_api_reservas__id_reserva__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar */
        get: operations["listar_api_reservas_get"];
        put?: never;
        /** Criar */
        post: operations["criar_api_reservas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reservas/{id_reserva}/cancelar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancelar */
        post: operations["cancelar_api_reservas__id_reserva__cancelar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DisponibilidadeResposta */
        DisponibilidadeResposta: {
            /** Id Recurso */
            id_recurso: number;
            /**
             * Dia
             * Format: date
             */
            dia: string;
            /** Lacunas */
            lacunas: components["schemas"]["Lacuna"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Lacuna */
        Lacuna: {
            /**
             * Inicio
             * Format: date-time
             */
            inicio: string;
            /**
             * Fim
             * Format: date-time
             */
            fim: string;
        };
        /** LoginEntrada */
        LoginEntrada: {
            /** Email Usuario */
            email_usuario: string;
            /** Senha */
            senha: string;
        };
        /** RecursoAtualizar */
        RecursoAtualizar: {
            /** Nome Recurso */
            nome_recurso?: string | null;
            /** Ocupacao */
            ocupacao?: number | null;
            /** Hora Func Inicio */
            hora_func_inicio?: string | null;
            /** Hora Func Fim */
            hora_func_fim?: string | null;
            /** Status Recurso */
            status_recurso?: ("ativo" | "inativo") | null;
        };
        /** RecursoCriar */
        RecursoCriar: {
            /** Nome Recurso */
            nome_recurso: string;
            /** Ocupacao */
            ocupacao: number;
            /**
             * Hora Func Inicio
             * Format: time
             */
            hora_func_inicio: string;
            /**
             * Hora Func Fim
             * Format: time
             */
            hora_func_fim: string;
        };
        /** RecursoResposta */
        RecursoResposta: {
            /** Id Recurso */
            id_recurso: number;
            /** Nome Recurso */
            nome_recurso: string;
            /** Ocupacao */
            ocupacao: number;
            /**
             * Hora Func Inicio
             * Format: time
             */
            hora_func_inicio: string;
            /**
             * Hora Func Fim
             * Format: time
             */
            hora_func_fim: string;
            /** Status Recurso */
            status_recurso: string;
            /** Fuso */
            fuso: string;
        };
        /** ReservaCriar */
        ReservaCriar: {
            /** Id Recurso */
            id_recurso: number;
            /** Convidados */
            convidados: number;
            /**
             * Inicio
             * Format: date-time
             */
            inicio: string;
            /**
             * Fim
             * Format: date-time
             */
            fim: string;
        };
        /** ReservaResposta */
        ReservaResposta: {
            /** Id Reserva */
            id_reserva: number;
            /** Id Usuario */
            id_usuario: number;
            /** Id Recurso */
            id_recurso: number;
            /** Convidados */
            convidados: number;
            /**
             * Inicio
             * Format: date-time
             */
            inicio: string;
            /**
             * Fim
             * Format: date-time
             */
            fim: string;
            /** Status Reserva */
            status_reserva: string;
            /** Cancelada Por Id Usuario */
            cancelada_por_id_usuario: number | null;
            /** Cancelada Em */
            cancelada_em: string | null;
        };
        /** TokenResposta */
        TokenResposta: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UsuarioCriar */
        UsuarioCriar: {
            /** Nome Usuario */
            nome_usuario: string;
            /**
             * Email Usuario
             * Format: email
             */
            email_usuario: string;
            /** Senha */
            senha: string;
            /**
             * Privilegio Usuario
             * @enum {string}
             */
            privilegio_usuario: "admin" | "usuario";
        };
        /** UsuarioResposta */
        UsuarioResposta: {
            /** Id Usuario */
            id_usuario: number;
            /** Nome Usuario */
            nome_usuario: string;
            /** Email Usuario */
            email_usuario: string;
            /** Privilegio Usuario */
            privilegio_usuario: string;
            /** Status Usuario */
            status_usuario: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    buscar_por_id_api_recursos__id_recurso__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_recurso: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecursoResposta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remover_api_recursos__id_recurso__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_recurso: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    atualizar_api_recursos__id_recurso__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_recurso: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecursoAtualizar"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecursoResposta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_api_recursos_get: {
        parameters: {
            query?: {
                limite?: number;
                deslocamento?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecursoResposta"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_api_recursos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecursoCriar"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecursoResposta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disponibilidade_api_recursos__id_recurso__disponibilidade_get: {
        parameters: {
            query: {
                dia: string;
            };
            header?: never;
            path: {
                id_recurso: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisponibilidadeResposta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResposta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    renovar_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResposta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_api_usuarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsuarioCriar"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioResposta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buscar_por_id_api_reservas__id_reserva__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_reserva: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservaResposta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_api_reservas_get: {
        parameters: {
            query?: {
                limite?: number;
                deslocamento?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservaResposta"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_api_reservas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservaCriar"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservaResposta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancelar_api_reservas__id_reserva__cancelar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_reserva: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservaResposta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
