"""cria as tabelas usuario, recurso e reserva

Revision ID: 8cf01df862a4
Revises:
Create Date: 2026-09-10 15:13:17.266458

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8cf01df862a4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.create_table(
        "recurso",
        sa.Column("id_recurso", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("nome_recurso", sa.String(length=30), nullable=False),
        sa.Column("ocupacao", sa.Integer(), nullable=False),
        sa.Column("hora_func_inicio", sa.Time(), nullable=False),
        sa.Column("hora_func_fim", sa.Time(), nullable=False),
        sa.Column("status_recurso", sa.String(length=30), nullable=False),
        sa.CheckConstraint(
            "status_recurso IN ('ativo', 'inativo')", name=op.f("ck_recurso_status")
        ),
        sa.CheckConstraint(
            "hora_func_inicio < hora_func_fim",
            name=op.f("ck_recurso_horario_dentro_do_dia"),
        ),
        sa.CheckConstraint("ocupacao > 0", name=op.f("ck_recurso_ocupacao_positiva")),
        sa.PrimaryKeyConstraint("id_recurso", name=op.f("pk_recurso")),
    )
    op.create_table(
        "usuario",
        sa.Column("id_usuario", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("privilegio_usuario", sa.String(length=15), nullable=False),
        sa.Column("nome_usuario", sa.String(length=30), nullable=False),
        sa.Column("email_usuario", sa.String(length=50), nullable=False),
        sa.Column(
            "senha_usuario_hash",
            sa.String(length=100),
            nullable=False,
            comment="Hash da senha do usuário, gerada por Argon 2",
        ),
        sa.Column("status_usuario", sa.String(length=30), nullable=False),
        sa.CheckConstraint(
            "privilegio_usuario IN ('admin', 'usuario')",
            name=op.f("ck_usuario_privilegio"),
        ),
        sa.CheckConstraint(
            "status_usuario IN ('ativo', 'inativo')", name=op.f("ck_usuario_status")
        ),
        sa.PrimaryKeyConstraint("id_usuario", name=op.f("pk_usuario")),
        sa.UniqueConstraint("email_usuario", name=op.f("uq_usuario_email_usuario")),
    )
    op.create_table(
        "reserva",
        sa.Column("id_reserva", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("id_usuario", sa.Integer(), nullable=False),
        sa.Column("id_recurso", sa.Integer(), nullable=False),
        sa.Column("convidados", sa.Integer(), nullable=False),
        sa.Column(
            "periodo",
            postgresql.TSTZRANGE(),
            nullable=False,
            comment="Ocupa um trecho de tempo com início e fim",
        ),
        sa.Column("status_reserva", sa.String(length=30), nullable=False),
        sa.Column("cancelada_por_id_usuario", sa.Integer(), nullable=True),
        sa.Column(
            "cancelada_em",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Tipo de instante com fuso",
        ),
        postgresql.ExcludeConstraint(
            (sa.column("id_recurso"), "="),
            (sa.column("periodo"), "&&"),
            where=sa.text("cancelada_em IS NULL"),
            using="gist",
            name="ex_reserva_sem_sobreposicao",
        ),
        sa.CheckConstraint(
            "status_reserva IN ('confirmada', 'cancelada')",
            name=op.f("ck_reserva_status"),
        ),
        sa.CheckConstraint(
            """
        (
            status_reserva = 'cancelada'
            AND cancelada_em IS NOT NULL
            AND cancelada_por_id_usuario IS NOT NULL
        )
        OR (
            status_reserva = 'confirmada'
            AND cancelada_em IS NULL
            AND cancelada_por_id_usuario IS NULL
        )
        """,
            name=op.f("ck_reserva_cancelamento"),
        ),
        sa.CheckConstraint(
            """
        NOT isempty(periodo)
        AND lower_inc(periodo)
        AND NOT upper_inc(periodo)
        AND NOT upper_inf(periodo)
        AND NOT lower_inf(periodo)
        """,
            name=op.f("ck_reserva_formato_semiaberto"),
        ),
        sa.CheckConstraint(
            "convidados > 0", name=op.f("ck_reserva_convidados_positivos")
        ),
        sa.ForeignKeyConstraint(
            ["cancelada_por_id_usuario"],
            ["usuario.id_usuario"],
            name=op.f("fk_reserva_cancelada_por_id_usuario_usuario"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["id_recurso"],
            ["recurso.id_recurso"],
            name=op.f("fk_reserva_id_recurso_recurso"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["id_usuario"],
            ["usuario.id_usuario"],
            name=op.f("fk_reserva_id_usuario_usuario"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id_reserva", name=op.f("pk_reserva")),
    )
    op.create_index(
        op.f("ix_reserva_cancelada_por_id_usuario"),
        "reserva",
        ["cancelada_por_id_usuario"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reserva_id_recurso"), "reserva", ["id_recurso"], unique=False
    )
    op.create_index(
        op.f("ix_reserva_id_usuario"), "reserva", ["id_usuario"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reserva_id_usuario"), table_name="reserva")
    op.drop_index(op.f("ix_reserva_id_recurso"), table_name="reserva")
    op.drop_index(op.f("ix_reserva_cancelada_por_id_usuario"), table_name="reserva")
    op.drop_table("reserva")
    op.drop_table("usuario")
    op.drop_table("recurso")
    # a btree_gist não é derrubada de propósito: o upgrade a cria com
    # IF NOT EXISTS, então ela pode ser anterior a esta migration --
    # desfazer o que talvez não tenhamos feito quebraria quem veio antes
    # ### end Alembic commands ###
