"""cria refresh_token

Revision ID: de451a039a1a
Revises: 8cf01df862a4
Create Date: 2026-09-18 17:18:28.749767

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de451a039a1a"
down_revision: Union[str, Sequence[str], None] = "8cf01df862a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_token",
        sa.Column(
            "id_refresh_token", sa.Integer(), sa.Identity(always=True), nullable=False
        ),
        sa.Column("id_usuario", sa.Integer(), nullable=False),
        sa.Column(
            "hash_token",
            sa.String(length=64),
            nullable=False,
            comment="Hash de 64 caracteres gerado por SHA-256",
        ),
        sa.Column(
            "familia_token",
            sa.UUID(),
            nullable=False,
            comment="De qual login este descende",
        ),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="instante em que o token foi emitido (no login ou na rotação)",
        ),
        sa.Column(
            "expira_em",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Depois disso o token não vale, mesmo revogado",
        ),
        sa.Column(
            "revogado_em",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="NULL permitido, e o nulo é o estado normal (vivo). "
            "Preenchido no logout, na rotação e na detecção de reuso",
        ),
        sa.CheckConstraint(
            "expira_em > criado_em",
            name=op.f("ck_refresh_token_expira_depois_de_criado"),
        ),
        sa.ForeignKeyConstraint(
            ["id_usuario"],
            ["usuario.id_usuario"],
            name=op.f("fk_refresh_token_id_usuario_usuario"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id_refresh_token", name=op.f("pk_refresh_token")),
        sa.UniqueConstraint("hash_token", name=op.f("uq_refresh_token_hash_token")),
    )
    op.create_index(
        op.f("ix_refresh_token_familia_token"),
        "refresh_token",
        ["familia_token"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_token_id_usuario"),
        "refresh_token",
        ["id_usuario"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refresh_token_id_usuario"), table_name="refresh_token")
    op.drop_index(op.f("ix_refresh_token_familia_token"), table_name="refresh_token")
    op.drop_table("refresh_token")
    # ### end Alembic commands ###
